### ISSUE TITLE
[BUG] Extraneous `run execute`

### ISSUE THREAD

**Issue by Nico314159** [WingedSeal/jmc#102]
## Describe the bug
The following code segment will have a `run execute` in the compiled output, which should be optimized out.

## To Reproduce [Steps to reproduce the behavior]
Compile the following code in JMC or on [try-out](https://jmc.wingedseal.com/try-out)
```ts
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] expand {
    tf2.batch_number:@s = execute on passengers 
                          run tf2.batch_number:@s 
                        = index::i * 1.0;
    team join player_motion.no_collide;
    tag @s remove tf2.new;
}
```

## Expected behavior [A clear and concise description of what you expected to happen.]
I expected it to compile to 
```mcfunction
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] store result score @s tf2.batch_number on passengers store result score @s tf2.batch_number run data get storage tf2:index i 1.0
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] run team join player_motion.no_collide
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] run tag @s remove tf2.new
```

## Actual behavior
Instead, it compiles to 
```mcfunction
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] run execute store result score @s tf2.batch_number on passengers store result score @s tf2.batch_number run data get storage tf2:index i 1.0
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] run team join player_motion.no_collide
execute as @e[type=axolotl,tag=tf2.new,tag=tf2.no_respawn] run tag @s remove tf2.new
```
Note how the first line contains a useless `run execute`.

## Screenshots
<img width="1387" alt="Screenshot 2024-05-27 at 13 18 10" src="https://github.com/WingedSeal/jmc/assets/26015841/3b044e6b-5ef1-4b7c-8db1-cf6172cee655">

## Desktop
- 2022 M2 MacBook Air running MacOS Sonoma 14.4.1

**Comment by WingedSeal** [comment]
Fixed in 76990b04a57c2be59061e83c10d4ca55a84ca848
