### ISSUE TITLE
[BUG] Cant use "execute if function".

### ISSUE THREAD

**Issue by FireBallMC3** [WingedSeal/jmc#116]
## Describe the bug
The compiler throws a exception when using "execute if function ..."

## To Reproduce

1. Write a command like "execute if function test() run say "Hello World";
2. Compile the code.

## Expected behavior
The compiler shouldn't throw an exception. Instead it should be translated to "execute if function namespace:test run say "Hello World""

## Desktop

Windows

## Additional context
I am using the pre released version for datapack version 48 support.

**Comment by Nico314159** [comment]
This is a feature request and a duplicate of #108
