### ISSUE TITLE
[FEATURE_REQUEST] Manual compiler bypass.

### ISSUE THREAD

**Issue by FireBallMC3** [WingedSeal/jmc#118]
## Description
A way to bypass the compiler when i throws a wrongfull exception.
Example:
`test();`
`raw {execute if data entity @s item run say item}`
`say "hi";`
Should compile to:
`function namespace:test`
`execute if data entity @s item run say item`
`say hi`

**Comment by Nico314159** [comment]
This already exists.

```
test();
JMC.put("execute if data entity @s item run say item");
say "hi";
```
