### ISSUE TITLE
[BUG] switch case does not accept negative number

### ISSUE THREAD

**Issue by bdke** [WingedSeal/jmc#14]
**Describe the bug**
switch case with negative number not worked as intended

**To Reproduce**
```
  switch ($rotation_1) {
      case 1:
          tp @s ~ ~ ~ ~ ~1;
      case -1:
          tp @s ~ ~ ~ ~ ~-1;
  }
```
It throws
```
JMCSyntaxException
In <FilePath>
Expected case number at line 140 col 22.
                case - <-
```

**Expected behavior**
accept neagative number as switch case

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows

**Additional context**
N/A

**Comment by WingedSeal** [comment]
The error message is wrong, but switch does not accept negative number as stated in the documents. I'll fix the error message.
