### ISSUE TITLE
Extends keyword

### ISSUE THREAD

**Issue by Zefyro** [WingedSeal/jmc#36]
## Inheriting properties from an already defined file using `extends` keyword
In simple terms, allow modifying values of a file created using the `new` keyword without copying the whole file.  
This would be really useful for custom advancements that are different by a single line or the likes.  
```js
new advancement(blue_reward) {
  "display": {
    "icon": {
      "item": "minecraft:blue_concrete"
    },
    "title": "Example",
    "description": "example",
    "frame": "goal"
  },
  "criteria": {
    "requirement": {
      "trigger": "minecraft:tick",
      "conditions": {
        "player": {
          "team": "blue"
        }
      }
    }
  },
  "rewards": {
    "function": "example:reward"
  }
}

new advancement(red_reward) extends(blue_reward) {
  "display": {
    "icon": {
      "item": "minecraft:red_concrete"
    },
  },
  "criteria": {
    "requirement": {
      "conditions": {
        "player": {
          "team": "red"
        }
      }
    }
  }
}
```
This would allow one to copy and modify files that require minor changes without completely copying the contents of the file.  
This also allows making the same changes to the files faster for example if the `reward` were changed to also include experience, all the files extending the parent would get the change.

**Comment by Nico314159** [comment]
+1, this would be a very useful feature
