### ISSUE TITLE
Add a dedicated "this" keyword for classes

### ISSUE THREAD

**Issue by w00tyd00d** [WingedSeal/jmc#45]
## Description
The addition of a dedicated `this` keyword could be used as a means to access the currently accessed "class" address when writing classes in JMC.

For example, instead of having to write this:

![image](https://github.com/WingedSeal/jmc/assets/66709693/b52f8160-1834-4cdb-b37e-1aaf700882f8)

You could just write it like this:

![image](https://github.com/WingedSeal/jmc/assets/66709693/dc6b42ac-4025-4f1e-8c23-b2eb269973d1)

**Comment by Nico314159** [comment]
+1

**Comment by WingedSeal** [comment]
https://github.com/WingedSeal/jmc/commit/0d824337b4421d8603572ffcee749c7d88b704d8
https://github.com/WingedSeal/jmc/commit/2920d3378c4b2c5d461eaf360c13c072f1f493d6
https://github.com/WingedSeal/jmc/commit/905ccf06fd52ada52a552d3ba6e10f56a91fec86
[Add a dedicated this keyword for classes](https://github.com/WingedSeal/jmc/commit/7ac9a78b26ee9de30544440ac7623e0963c6ff4c)
