### ISSUE TITLE
Switch cases throw an exception when using scoreboard:selector values

### ISSUE THREAD

**Issue by w00tyd00d** [WingedSeal/jmc#48]
## Describe the bug
When using a scoreboard value (using the `scoreboard:selector` syntax) as a variable in a switch case, the compiler will throw a syntax exception saying the colon is an unexpected token.

## To Reproduce
1. Use a `scoreboard:selector` value in a switch case and try to compile the project.

## Screenshots
![image](https://github.com/WingedSeal/jmc/assets/66709693/746025fa-8e46-42bc-920d-edf5918dce93)
![image](https://github.com/WingedSeal/jmc/assets/66709693/d72aa84e-8fdc-4413-910d-d86233b7ec69)

## Desktop
- Windows 10

**Comment by Nico314159** [comment]
This is intended behavior. I'll see what I can do but WingedSeal has already said that you should just copy the variable over with `$test = test_objective:value`.

**Comment by w00tyd00d** [comment]
Oh is it? Because the documentation on the website says using the `scoreboard:selector` syntax is allowed.

To quote:
"Switch Case will run commands according to the value of given variable/objective:selector."

That's not to say you're wrong! But one or the other should be corrected.

**Comment by Nico314159** [comment]
WingedSeal already said that was a documentation error

**Comment by Nico314159** [comment]
Update: I managed to figure it out, it was actually simpler than I expected.

**Comment by w00tyd00d** [comment]
I was actually just about to reply when I saw the comment lol awesome! I appreciate it, it really helps to have variables be grouped by scoreboards for debugging purposes when testing in-game, but it wouldn't have been the end of the world if it had to rely on a quick variable declaration to get it to work.

I do think it will be more intuitive to include it, tho.
