### ISSUE TITLE
[BUG] $#<variable> had been allowed to declared but not allowed to use

### ISSUE THREAD

**Issue by boon4681** [WingedSeal/jmc#5]
$#<variable> had been allowed to declared
compiler said it's fine to do something like this.
```js
$#hi= 5;
```
![image](https://user-images.githubusercontent.com/46645814/200169406-4889823d-6284-4ff1-b44b-b8c19af5d947.png)
btw, compiler screams when I try to use it.

```js
$#hi= 5;

function hello (){
    if ($#hi>5 ) {
        hello();
    }
}
```
![image](https://user-images.githubusercontent.com/46645814/200169514-9964ab3a-9b24-407d-bd5e-a5676fe736d1.png)

**Comment by WingedSeal** [comment]
Fixed in v1.2.5
