### ISSUE TITLE
[BUG] `weather clear` syntax does not work

### ISSUE THREAD

**Issue by TM10YMhp** [WingedSeal/jmc#86]
## Describe the bug

I tried to use `weather clear` but it only lets me use `execute run weather clear`.

## To Reproduce
[Steps to reproduce the behavior]

1. use `weather clear`
2. compile

## Expected behavior

Allow the use of `weather clear`.

## Screenshots

![weather_clear](https://github.com/WingedSeal/jmc/assets/91300213/47078222-be0d-490a-b529-90ac6c814c8f)

## Desktop

- Windows 10

**Comment by WingedSeal** [comment]
fixed in https://github.com/WingedSeal/jmc/commit/1e52ec5192ea38629ae52b493cb6cc640025f34e
