### ISSUE TITLE
[BUG] `Advancement.grant()` does not detect advancements

### ISSUE THREAD

**Issue by TM10YMhp** [WingedSeal/jmc#87]
## Describe the bug

when using `Advancement.grant(@s, only, story/enter_the_end, minecraft)` no advancement found

## To Reproduce

1. use `Advancement.grant(@a, only, story/enter_the_end, minecraft)`
2. compile

## Expected behavior

`Advancement.grant()` should detect advancements

## Screenshots

![advancement_grant](https://github.com/WingedSeal/jmc/assets/91300213/9ba82e7c-e9af-412e-898f-5138c0af1b10)

## Desktop

- Windows 10

**Comment by WingedSeal** [comment]
fixed in https://github.com/WingedSeal/jmc/commit/dcdc812467ff71b420614f4c39186f9cff40bd0d
